/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
export const Project = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
});
export const Experience = IDL.Record({
  'duration' : IDL.Text,
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'contacts' : IDL.Vec(Contact),
  'tagline' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'name' : IDL.Text,
  'experience' : IDL.Vec(Experience),
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'updateBasicInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContacts' : IDL.Func([IDL.Vec(Contact)], [], []),
  'updateExperience' : IDL.Func([IDL.Vec(Experience)], [], []),
  'updateProjects' : IDL.Func([IDL.Vec(Project)], [], []),
  'updateSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
  });
  const Experience = IDL.Record({
    'duration' : IDL.Text,
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'contacts' : IDL.Vec(Contact),
    'tagline' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'name' : IDL.Text,
    'experience' : IDL.Vec(Experience),
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'updateBasicInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContacts' : IDL.Func([IDL.Vec(Contact)], [], []),
    'updateExperience' : IDL.Func([IDL.Vec(Experience)], [], []),
    'updateProjects' : IDL.Func([IDL.Vec(Project)], [], []),
    'updateSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };