/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact { 'url' : string, 'platform' : string }
export interface Experience {
  'duration' : string,
  'role' : string,
  'description' : string,
  'company' : string,
}
export interface Profile {
  'bio' : string,
  'title' : string,
  'contacts' : Array<Contact>,
  'tagline' : string,
  'projects' : Array<Project>,
  'name' : string,
  'experience' : Array<Experience>,
  'skills' : Array<string>,
}
export interface Project {
  'title' : string,
  'link' : [] | [string],
  'description' : string,
}
export interface _SERVICE {
  'getProfile' : ActorMethod<[], Profile>,
  'updateBasicInfo' : ActorMethod<[string, string, string, string], undefined>,
  'updateContacts' : ActorMethod<[Array<Contact>], undefined>,
  'updateExperience' : ActorMethod<[Array<Experience>], undefined>,
  'updateProjects' : ActorMethod<[Array<Project>], undefined>,
  'updateSkills' : ActorMethod<[Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];