/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Profile {
    bio: string;
    title: string;
    contacts: Array<Contact>;
    tagline: string;
    projects: Array<Project>;
    name: string;
    experience: Array<Experience>;
    skills: Array<string>;
}
export interface Project {
    title: string;
    link?: string;
    description: string;
}
export interface Experience {
    duration: string;
    role: string;
    description: string;
    company: string;
}
export interface Contact {
    url: string;
    platform: string;
}
export interface backendInterface {
    getProfile(): Promise<Profile>;
    updateBasicInfo(newName: string, newTitle: string, newTagline: string, newBio: string): Promise<void>;
    updateContacts(newContacts: Array<Contact>): Promise<void>;
    updateExperience(newExperience: Array<Experience>): Promise<void>;
    updateProjects(newProjects: Array<Project>): Promise<void>;
    updateSkills(newSkills: Array<string>): Promise<void>;
}
import type { Contact as _Contact, Experience as _Experience, Profile as _Profile, Project as _Project } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_Profile_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_Profile_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBasicInfo(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBasicInfo(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBasicInfo(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateContacts(arg0: Array<Contact>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContacts(arg0);
            return result;
        }
    }
    async updateExperience(arg0: Array<Experience>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExperience(arg0);
            return result;
        }
    }
    async updateProjects(arg0: Array<Project>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjects(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjects(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSkills(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkills(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkills(arg0);
            return result;
        }
    }
}
function from_candid_Profile_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    title: string;
    contacts: Array<_Contact>;
    tagline: string;
    projects: Array<_Project>;
    name: string;
    experience: Array<_Experience>;
    skills: Array<string>;
}): {
    bio: string;
    title: string;
    contacts: Array<Contact>;
    tagline: string;
    projects: Array<Project>;
    name: string;
    experience: Array<Experience>;
    skills: Array<string>;
} {
    return {
        bio: value.bio,
        title: value.title,
        contacts: value.contacts,
        tagline: value.tagline,
        projects: from_candid_vec_n3(_uploadFile, _downloadFile, value.projects),
        name: value.name,
        experience: value.experience,
        skills: value.skills
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    link: [] | [string];
    description: string;
}): {
    title: string;
    link?: string;
    description: string;
} {
    return {
        title: value.title,
        link: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.link)),
        description: value.description
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Project_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    link?: string;
    description: string;
}): {
    title: string;
    link: [] | [string];
    description: string;
} {
    return {
        title: value.title,
        link: value.link ? candid_some(value.link) : candid_none(),
        description: value.description
    };
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Project>): Array<_Project> {
    return value.map((x)=>to_candid_Project_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
